name = "libapp"
main = "src/index.js"
compatibility_date = "2024-02-14"

[[d1_databases]]
binding = "DB"
database_name = "lib-db"
database_id = "xxxx-xxxx-xxxx-xxxx" # User will need to replace this with their actual DB ID
